const express= require("express")
const app = express()
const endroute = require("./endroute")
const dateMiddleware =require("../middlewares/horaMiddleware")
// const validarHora = require("..middlewares/validarHora")
app.use(dateMiddleware)
app.use("/",endroute,dateMiddleware)
app.listen(3000,()=>{
    console.log ("EL Servidor se esta ejecutando en el http://localhost:3000/")
})